name: Unit Tests

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "*.md"

jobs:
  run_tests:
    name: Run tests
    runs-on: macos-12
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Run tests
        run: |
          swift test
